/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_assets_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        /** Create Asset */
        post: operations["create_asset_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        /** Update Asset */
        put: operations["update_asset_api_v1_assets__asset_id__put"];
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_v1_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Credentials
         * @description List credentials with status only — no keys exposed.
         */
        get: operations["list_credentials_api_v1_credentials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/{provider}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Trigger sync for a provider (placeholder).
         */
        post: operations["trigger_sync_api_v1_credentials__provider__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finance/bank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bank Transactions */
        get: operations["list_bank_transactions_api_v1_finance_bank_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finance/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Card Transactions */
        get: operations["list_card_transactions_api_v1_finance_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Snapshot */
        post: operations["import_snapshot_api_v1_snapshots_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_api_v1_snapshots_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Snapshots */
        get: operations["compare_snapshots_api_v1_snapshots_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_v1_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_v1_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        /** Delete Snapshot */
        delete: operations["delete_snapshot_api_v1_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetCreate */
        AssetCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["AssetType"];
            /**
             * Institution
             * @default
             */
            institution: string;
            /**
             * Balance
             * @default 0
             */
            balance: number | string;
            /** @default KRW */
            currency: components["schemas"]["Currency"];
        };
        /** AssetEntryResponse */
        AssetEntryResponse: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Product Name */
            product_name: string;
            /** Amount */
            amount: string;
        };
        /** AssetResponse */
        AssetResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            type: components["schemas"]["AssetType"];
            /** Institution */
            institution: string;
            /** Balance */
            balance: string;
            currency: components["schemas"]["Currency"];
            /** Last Synced */
            last_synced: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AssetSummary */
        AssetSummary: {
            /** Total Krw */
            total_krw: string;
            /** Total Usd */
            total_usd: string;
            /** Breakdown */
            breakdown: {
                [key: string]: string;
            };
        };
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: "BANK" | "STOCK" | "CRYPTO" | "CARD" | "CASH";
        /** AssetUpdate */
        AssetUpdate: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["AssetType"] | null;
            /** Institution */
            institution?: string | null;
            /** Balance */
            balance?: number | string | null;
            currency?: components["schemas"]["Currency"] | null;
        };
        /** BankTransactionResponse */
        BankTransactionResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Asset Id */
            asset_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Description */
            description: string;
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_import_snapshot_api_v1_snapshots_import_post */
        Body_import_snapshot_api_v1_snapshots_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CardTransactionResponse */
        CardTransactionResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Asset Id */
            asset_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Merchant */
            merchant: string;
            /** Amount */
            amount: string;
            /** Category */
            category: string;
            /** Installment */
            installment: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompareResponse */
        CompareResponse: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            diff: components["schemas"]["SnapshotDiff"];
        };
        /** CredentialStatus */
        CredentialStatus: {
            /** Id */
            id: number;
            /** Provider */
            provider: string;
            /** Is Active */
            is_active: boolean;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "KRW" | "USD";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsuranceEntryResponse */
        InsuranceEntryResponse: {
            /** Id */
            id: number;
            /** Insurer */
            insurer: string;
            /** Product Name */
            product_name: string;
            /** Status */
            status: string;
            /** Total Paid */
            total_paid: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
        };
        /** InvestmentEntryResponse */
        InvestmentEntryResponse: {
            /** Id */
            id: number;
            /** Broker */
            broker: string;
            /** Product Name */
            product_name: string;
            /** Invested Amount */
            invested_amount: string;
            /** Current Value */
            current_value: string;
            /** Return Rate */
            return_rate: string | null;
        };
        /** LoanEntryResponse */
        LoanEntryResponse: {
            /** Id */
            id: number;
            /** Lender */
            lender: string;
            /** Product Name */
            product_name: string;
            /** Principal */
            principal: string;
            /** Balance */
            balance: string;
            /** Interest Rate */
            interest_rate: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
        };
        /** PaginatedResponse[AssetResponse] */
        PaginatedResponse_AssetResponse_: {
            /** Items */
            items: components["schemas"]["AssetResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[BankTransactionResponse] */
        PaginatedResponse_BankTransactionResponse_: {
            /** Items */
            items: components["schemas"]["BankTransactionResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[CardTransactionResponse] */
        PaginatedResponse_CardTransactionResponse_: {
            /** Items */
            items: components["schemas"]["CardTransactionResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[SnapshotSummaryResponse] */
        PaginatedResponse_SnapshotSummaryResponse_: {
            /** Items */
            items: components["schemas"]["SnapshotSummaryResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** SnapshotDetailResponse */
        SnapshotDetailResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Source */
            source: string;
            /** Credit Score */
            credit_score: number | null;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Asset Entries */
            asset_entries: components["schemas"]["AssetEntryResponse"][];
            /** Investment Entries */
            investment_entries: components["schemas"]["InvestmentEntryResponse"][];
            /** Loan Entries */
            loan_entries: components["schemas"]["LoanEntryResponse"][];
            /** Insurance Entries */
            insurance_entries: components["schemas"]["InsuranceEntryResponse"][];
        };
        /** SnapshotDiff */
        SnapshotDiff: {
            /** Credit Score */
            credit_score: number;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
        };
        /** SnapshotSummaryResponse */
        SnapshotSummaryResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Source */
            source: string;
            /** Credit Score */
            credit_score: number | null;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SyncTriggerResponse */
        SyncTriggerResponse: {
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** TrendPointResponse */
        TrendPointResponse: {
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Credit Score */
            credit_score: number | null;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_summary_api_v1_assets_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSummary"];
                };
            };
        };
    };
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_AssetResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asset_api_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_v1_assets__asset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_api_v1_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialStatus"][];
                };
            };
        };
    };
    trigger_sync_api_v1_credentials__provider__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bank_transactions_api_v1_finance_bank_get: {
        parameters: {
            query?: {
                asset_id?: number | null;
                start?: string | null;
                end?: string | null;
                category?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_BankTransactionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_card_transactions_api_v1_finance_card_get: {
        parameters: {
            query?: {
                asset_id?: number | null;
                start?: string | null;
                end?: string | null;
                category?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_CardTransactionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_snapshot_api_v1_snapshots_import_post: {
        parameters: {
            query?: {
                password?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_snapshot_api_v1_snapshots_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_api_v1_snapshots_trend_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPointResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_snapshots_api_v1_snapshots_compare_get: {
        parameters: {
            query: {
                from_date: string;
                to_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_snapshots_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_SnapshotSummaryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_v1_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_api_v1_snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
