/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Snapshot */
        post: operations["import_snapshot_api_v1_snapshots_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_api_v1_snapshots_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_v1_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ledger Entries */
        get: operations["get_ledger_entries_api_v1_snapshots__snapshot_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_v1_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        /** Delete Snapshot */
        delete: operations["delete_snapshot_api_v1_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Asset Entry */
        post: operations["add_asset_entry_api_v1_snapshots__snapshot_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}/assets/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Asset Entry */
        delete: operations["delete_asset_entry_api_v1_snapshots__snapshot_id__assets__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange/upbit/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upbit Balances */
        get: operations["get_upbit_balances_api_v1_exchange_upbit_balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange/kis/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kis Balance */
        get: operations["get_kis_balance_api_v1_exchange_kis_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetEntryCreate */
        AssetEntryCreate: {
            /** Category */
            category: string;
            /** Product Name */
            product_name: string;
            /** Amount */
            amount: number | string;
        };
        /** AssetEntryResponse */
        AssetEntryResponse: {
            /** Id */
            id: number;
            /** Category */
            category: string;
            /** Product Name */
            product_name: string;
            /** Amount */
            amount: string;
        };
        /** Body_import_snapshot_api_v1_snapshots_import_post */
        Body_import_snapshot_api_v1_snapshots_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsuranceEntryResponse */
        InsuranceEntryResponse: {
            /** Id */
            id: number;
            /** Insurer */
            insurer: string;
            /** Product Name */
            product_name: string;
            /** Status */
            status: string;
            /** Total Paid */
            total_paid: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
        };
        /** InvestmentEntryResponse */
        InvestmentEntryResponse: {
            /** Id */
            id: number;
            /** Broker */
            broker: string;
            /** Product Name */
            product_name: string;
            /** Invested Amount */
            invested_amount: string;
            /** Current Value */
            current_value: string;
            /** Return Rate */
            return_rate: string | null;
        };
        /** KisBalanceSummaryResponse */
        KisBalanceSummaryResponse: {
            /** Holdings */
            holdings: components["schemas"]["KisHoldingResponse"][];
            /** Tot Evlu Amt */
            tot_evlu_amt: string;
            /** Pchs Amt Smtl Amt */
            pchs_amt_smtl_amt: string;
            /** Evlu Pfls Smtl Amt */
            evlu_pfls_smtl_amt: string;
            /** Nass Amt */
            nass_amt: string;
        };
        /** KisHoldingResponse */
        KisHoldingResponse: {
            /** Pdno */
            pdno: string;
            /** Prdt Name */
            prdt_name: string;
            /** Hldg Qty */
            hldg_qty: string;
            /** Pchs Avg Pric */
            pchs_avg_pric: string;
            /** Pchs Amt */
            pchs_amt: string;
            /** Prpr */
            prpr: string;
            /** Evlu Amt */
            evlu_amt: string;
            /** Evlu Pfls Amt */
            evlu_pfls_amt: string;
            /** Evlu Pfls Rt */
            evlu_pfls_rt: string;
        };
        /** LedgerEntryResponse */
        LedgerEntryResponse: {
            /** Id */
            id: number;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Time */
            entry_time: string | null;
            /** Entry Type */
            entry_type: string;
            /** Major Category */
            major_category: string;
            /** Minor Category */
            minor_category: string | null;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Payment Method */
            payment_method: string | null;
            /** Memo */
            memo: string | null;
        };
        /** LoanEntryResponse */
        LoanEntryResponse: {
            /** Id */
            id: number;
            /** Lender */
            lender: string;
            /** Product Name */
            product_name: string;
            /** Principal */
            principal: string;
            /** Balance */
            balance: string;
            /** Interest Rate */
            interest_rate: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
        };
        /** PaginatedResponse[LedgerEntryResponse] */
        PaginatedResponse_LedgerEntryResponse_: {
            /** Items */
            items: components["schemas"]["LedgerEntryResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PaginatedResponse[SnapshotSummaryResponse] */
        PaginatedResponse_SnapshotSummaryResponse_: {
            /** Items */
            items: components["schemas"]["SnapshotSummaryResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** SnapshotDetailResponse */
        SnapshotDetailResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /**
             * Snapshot Date
             * Format: date-time
             */
            snapshot_date: string;
            /** Source */
            source: string;
            /** Credit Score */
            credit_score: number | null;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
            /** Filename Stem */
            filename_stem: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Asset Entries */
            asset_entries: components["schemas"]["AssetEntryResponse"][];
            /** Investment Entries */
            investment_entries: components["schemas"]["InvestmentEntryResponse"][];
            /** Loan Entries */
            loan_entries: components["schemas"]["LoanEntryResponse"][];
            /** Insurance Entries */
            insurance_entries: components["schemas"]["InsuranceEntryResponse"][];
            /**
             * Ledger Count
             * @default 0
             */
            ledger_count: number;
        };
        /** SnapshotSummaryResponse */
        SnapshotSummaryResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /**
             * Snapshot Date
             * Format: date-time
             */
            snapshot_date: string;
            /** Source */
            source: string;
            /** Credit Score */
            credit_score: number | null;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
            /** Filename Stem */
            filename_stem: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TrendPointResponse */
        TrendPointResponse: {
            /**
             * Snapshot Date
             * Format: date-time
             */
            snapshot_date: string;
            /** Credit Score */
            credit_score: number | null;
            /** Total Assets */
            total_assets: string;
            /** Total Liabilities */
            total_liabilities: string;
            /** Net Worth */
            net_worth: string;
        };
        /** UpbitBalanceResponse */
        UpbitBalanceResponse: {
            /** Currency */
            currency: string;
            /** Balance */
            balance: string;
            /** Locked */
            locked: string;
            /** Avg Buy Price */
            avg_buy_price: string;
            /** Avg Buy Price Modified */
            avg_buy_price_modified: boolean;
            /** Unit Currency */
            unit_currency: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_snapshot_api_v1_snapshots_import_post: {
        parameters: {
            query?: {
                password?: string | null;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_snapshot_api_v1_snapshots_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_api_v1_snapshots_trend_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPointResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_snapshots_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_SnapshotSummaryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_entries_api_v1_snapshots__snapshot_id__ledger_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_LedgerEntryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_v1_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_api_v1_snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_asset_entry_api_v1_snapshots__snapshot_id__assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_entry_api_v1_snapshots__snapshot_id__assets__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upbit_balances_api_v1_exchange_upbit_balances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpbitBalanceResponse"][];
                };
            };
        };
    };
    get_kis_balance_api_v1_exchange_kis_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KisBalanceSummaryResponse"];
                };
            };
        };
    };
}
